version: '3.4'

services:
  production.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  basket.api:
   container_name: basket.api
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
   depends_on:
       - basketdb
   ports:
      - "8000:80"

  basketdb:
   container_name: basketdb
   restart: always
   ports:
      - "6379:6379"

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
     
    ports:
      - "80"

