version: '3.4'

services:

 orderdb:
  image: "mcr.microsoft.com/mssql/server:2019-latest"

 order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Orders/Order.API/Dockerfile


