version: '3.4'

services:

 orderdb:
  container_name: orderdb
  environment:
    SA_PASSWORD: "password"
    ACCEPT_EULA: "Y"
    restart: always
  ports:
    - "1433:1433"

 order.api:
   container_name: order.api
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
      "ConnectionStrings:OrderingConnectionString:orderdb;Initial Catalog=Ordersdb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
   ports:
      - "80"
