version: '3.4'

services:
  production.api:
    image: ${DOCKER_REGISTRY-}productionapi
    build:
      context: .
      dockerfile: src/Production/Production.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Orders/Order.API/Dockerfile

