version: '3.4'

services:

 sqlservdb:
  image: "mcr.microsoft.com/mssql/server:2019-latest"

 rabbitmq:
  image: "rabbitmq:latest"

 order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Orders/Order.API/Dockerfile

 inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Inventory/Inventory.API/Dockerfile


 production.api:
    image: ${DOCKER_REGISTRY-}productionapi
    build:
      context: .
      dockerfile: src/Production/Production.API/Dockerfile

